"""Resize varchar

Revision ID: 42c3f908f99d
Revises: 72598f7bafe4
Create Date: 2025-07-15 22:46:41.410233

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "42c3f908f99d"
down_revision: Union[str, Sequence[str], None] = "72598f7bafe4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_apscheduler_jobs_next_run_time"), table_name="apscheduler_jobs")
    op.drop_table("apscheduler_jobs")
    op.alter_column(
        "subscriptions",
        "vpn_key",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "subscriptions",
        "outline_key_id",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "tariffs",
        "price",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=7, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "username",
        existing_type=sa.VARCHAR(length=40),
        type_=sa.String(length=32),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "referral_code",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.String(length=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "referral_code",
        existing_type=sa.String(length=10),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "username",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=40),
        existing_nullable=False,
    )
    op.alter_column(
        "tariffs",
        "price",
        existing_type=sa.Numeric(precision=7, scale=2),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "subscriptions",
        "outline_key_id",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=64),
        existing_nullable=True,
    )
    op.alter_column(
        "subscriptions",
        "vpn_key",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
    )
    op.create_table(
        "apscheduler_jobs",
        sa.Column("id", sa.VARCHAR(length=191), autoincrement=False, nullable=False),
        sa.Column(
            "next_run_time", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column("job_state", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("apscheduler_jobs_pkey")),
    )
    op.create_index(
        op.f("ix_apscheduler_jobs_next_run_time"),
        "apscheduler_jobs",
        ["next_run_time"],
        unique=False,
    )
    # ### end Alembic commands ###
