"""add outline_key_id to subscriptions

Revision ID: 72598f7bafe4
Revises: a046bd86f59b
Create Date: 2025-07-09 21:18:09.556679

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72598f7bafe4"
down_revision: Union[str, Sequence[str], None] = "a046bd86f59b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscriptions", sa.Column("outline_key_id", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "outline_key_id")
    # ### end Alembic commands ###
