"""Initial users, referral_program, subscriptions, tariffs

Revision ID: c23b8d78bd65
Revises:
Create Date: 2025-07-06 14:04:49.929334

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c23b8d78bd65"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tariffs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=16), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_tariff_name"),
    )
    op.create_index(op.f("ix_tariffs_is_active"), "tariffs", ["is_active"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=40), nullable=False),
        sa.Column("referral_code", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("referral_code"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "referrals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("referrer_id", sa.BigInteger(), nullable=False),
        sa.Column("referred_id", sa.BigInteger(), nullable=False),
        sa.Column("bonus_days", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["referred_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["referrer_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("referred_id", name="uq_referred_user"),
        sa.UniqueConstraint("referrer_id", "referred_id", name="uq_referral_pair"),
    )
    op.create_index(
        "idx_referrer_referred", "referrals", ["referrer_id", "referred_id"], unique=False
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("tariff_id", sa.Integer(), nullable=False),
        sa.Column("vpn_key", sa.String(length=64), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("cnt_payments", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tariff_id"], ["tariffs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )

    # ### установка функции и триггера для автоматического обновления поля updated_at ###
    # fmt: off
    # flake8: noqa
    op.execute(
        """
        CREATE OR REPLACE FUNCTION update_updated_at_column()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = timezone('utc', now());
            RETURN NEW;
        END;
        $$ language 'plpgsql';
        """
    )  # Создание функции для обновления updated_at
    op.execute(
        """
        CREATE TRIGGER set_updated_at
        BEFORE UPDATE ON subscriptions
        FOR EACH ROW
        EXECUTE PROCEDURE update_updated_at_column();
        """
    )
    # fmt: on
    # Создание триггера set_updated_at

    op.create_index("idx_sub_end_date", "subscriptions", ["end_date"], unique=False)
    op.create_index("idx_sub_user_active", "subscriptions", ["user_id", "is_active"], unique=False)
    op.create_index(
        op.f("ix_subscriptions_is_active"), "subscriptions", ["is_active"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### команды для удаления триггера и функции ###
    op.execute("DROP TRIGGER IF EXISTS set_updated_at ON subscriptions;")  # удаляем триггер
    op.execute("DROP FUNCTION IF EXISTS update_updated_at_column();")  # удаляем функцию
    # ### конец удаления триггера ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscriptions_is_active"), table_name="subscriptions")
    op.drop_index("idx_sub_user_active", table_name="subscriptions")
    op.drop_index("idx_sub_end_date", table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index("idx_referrer_referred", table_name="referrals")
    op.drop_table("referrals")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tariffs_is_active"), table_name="tariffs")
    op.drop_table("tariffs")
    # ### end Alembic commands ###
